## Basic Configuration

baseurl = "https://www.mbdtf.xyz/"
builddrafts = false
canonifyurls = false
languageCode = "zh-cn"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = ""
title = "MBDTF"

theme = "hugo-goa"

## Hugo Built-in Features
disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
googleAnalytics = "UA-142497661-1"
enableRobotsTXT = true

## Site Settings
[params]
# author = "Todd"
intro = "Blog"
description = "Software Engineer"
authorimage = "headshot.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Simple minimalist theme"
keywords = "minimalist,blog,goa,hugo,developer"

## Social Accounts
[params.social]
github = "TylerJackk"
twitter = "toddd01419346"
email = "liwep.x@gmail.com"

## Extras
[params.extra]
copyright = "© 2021. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)."
poweredby = true
highlightjs = true
socialmarkup = true
toc = true
displayrssicon = true

## Main Menu
[[menu.main]]
    name = "blog"
    weight = 100
    identifier = "blog"
    url = "/blog/"
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 200
    url = "/about/"
[[menu.main]]
    name = "coderag"
    identifier = "coderag"
    weight = 300
    url = "/coderag/"
